version: '3.1'

services:

  tests:
    container_name: utopia-pools-tests
    build:
      context: .
    networks:
      - database
    volumes:
      - ./:/usr/src/code
    ports:
      - "8708:8708"

networks:
  database:
